/** 
 * @typedef {Object} LASTNAME_DATA
 * @param {String} male
 * @param {String} female
 * @param {String} other
 */

const LASTNAMES = [
    { male: "Bielawski", female: "Bielawska", other: "Bielawskie" },
    { male: "Dudekcki", female: "Dudekcka", other: "Dudekckie" },
    { male: "Rzeka", female: "Rzeka", other: "Rzeka" },
    { male: "Kaczmarek", female: "Kaczmarek", other: "Kaczmarek" },
    { male: "Zima", female: "Zima", other: "Zima" },
    { male: "Wieczor", female: "Wieczor", other: "Wieczor" },
    { male: "Zając", female: "Zając", other: "Zając" },
    { male: "Urbanek", female: "Urbanek", other: "Urbanek" },
    { male: "Zawadzki", female: "Zawadzka", other: "Zawadzkie" },
    { male: "Marcinkowski", female: "Marcinkowska", other: "Marcinkowskie" },
    { male: "Malinowski", female: "Malinowska", other: "Malinowskie" },
    { male: "Musiałek", female: "Musiałek", other: "Musiałek" },
    { male: "Kołodziejski", female: "Kołodziejska", other: "Kołodziejskie" },
    { male: "Dąbrowski", female: "Dąbrowska", other: "Dąbrowskie" },
    { male: "Lewandowski", female: "Lewandowski", other: "Lewandowski" },
    { male: "Adamczyk", female: "Adamczyk", other: "Adamczyk" },
    { male: "Walczak", female: "Walczak", other: "Walczak" },
    { male: "Grabowski", female: "Grabowska", other: "Grabowskie" },
    { male: "Bielawski", female: "Bielawska", other: "Bielawskie" },
    { male: "Jankowski", female: "Jankowska", other: "Jankowskie" },
    { male: "Wasilewski", female: "Wasilewski", other: "Wasilewski" },
    { male: "Gwiazda", female: "Gwiazda", other: "Gwiazda" },
    { male: "Wójcik", female: "Wójcik", other: "Wójcik" },
    { male: "Majewski", female: "Majewska", other: "Majewskie" },
    { male: "Gajewski", female: "Gajewska", other: "Gajewskie" },
    { male: "Nowicki", female: "Nowicka", other: "Nowickie" },
    { male: "Brzoza", female: "Brzoza", other: "Brzoza" },
    { male: "Kucharski", female: "Kucharska", other: "Kucharskie" },
    { male: "Miedź", female: "Miedź", other: "Miedź" },
    { male: "Jesień", female: "Jesień", other: "Jesień" },
    { male: "Lisicki", female: "Lisicka", other: "Lisickie" },
    { male: "Makowski", female: "Makowska", other: "Makowskie" },
    { male: "Łuczarski", female: "Łuczarska", other: "Łuczarskie" },
    { male: "Lisski", female: "Lisska", other: "Lisskie" },
    { male: "Piasek", female: "Piasek", other: "Piasek" },
    { male: "Grom", female: "Grom", other: "Grom" },
    { male: "Wróbel", female: "Wróbel", other: "Wróbel" },
    { male: "Orzeł", female: "Orzeł", other: "Orzeł" },
    { male: "Borowskiski", female: "Borowskiska", other: "Borowskiskie" },
    { male: "Kowal", female: "Kowal", other: "Kowal" },
    { male: "Nowicki", female: "Nowicka", other: "Nowickie" },
    { male: "Brzeziński", female: "Brzezińska", other: "Brzezińskie" },
    { male: "Marciniak", female: "Marciniak", other: "Marciniak" },
    { male: "Stanickiek", female: "Stanickiek", other: "Stanickiek" },
    { male: "Romanowskicki", female: "Romanowskicka", other: "Romanowskickie" },
    { male: "Wasilewski", female: "Wasilewska", other: "Wasilewskie" },
    { male: "Mróz", female: "Mróz", other: "Mróz" },
    { male: "Szczepański", female: "Szczepański", other: "Szczepański" },
    { male: "Baranowski", female: "Baranowski", other: "Baranowski" },
    { male: "Dąb", female: "Dąb", other: "Dąb" },
    { male: "Bąk", female: "Bąk", other: "Bąk" },
    { male: "Borowski", female: "Borowska", other: "Borowskie" },
    { male: "Kaczmarekek", female: "Kaczmarekek", other: "Kaczmarekek" },
    { male: "Gajewski", female: "Gajewska", other: "Gajewskie" },
    { male: "Ratajczak", female: "Ratajczak", other: "Ratajczak" },
    { male: "Gajdacki", female: "Gajdacka", other: "Gajdackie" },
    { male: "Marcinkowski", female: "Marcinkowska", other: "Marcinkowskie" },
    { male: "Łuczak", female: "Łuczak", other: "Łuczak" },
    { male: "Zieliński", female: "Zielińska", other: "Zielińskie" },
    { male: "Popiół", female: "Popiół", other: "Popiół" },
    { male: "Baranowskicki", female: "Baranowskicka", other: "Baranowskickie" },
    { male: "Sadowskickiak", female: "Sadowskickiak", other: "Sadowskickiak" },
    { male: "Szabla", female: "Szabla", other: "Szabla" },
    { male: "Wasilewskickiekak", female: "Wasilewskickiekak", other: "Wasilewskickiekak" },
    { male: "Rów", female: "Rów", other: "Rów" },
    { male: "Borkowskiak", female: "Borkowskiak", other: "Borkowskiak" },
    { male: "Tomaszewski", female: "Tomaszewski", other: "Tomaszewski" },
    { male: "Lewandowski", female: "Lewandowski", other: "Lewandowski" },
    { male: "Ziółkowskiski", female: "Ziółkowskiska", other: "Ziółkowskiskie" },
    { male: "Michalski", female: "Michalska", other: "Michalskie" },
    { male: "Tomaszewskicki", female: "Tomaszewskicka", other: "Tomaszewskickie" },
    { male: "Łąka", female: "Łąka", other: "Łąka" },
    { male: "Chojnacki", female: "Chojnacka", other: "Chojnackie" },
    { male: "Wiśniewski", female: "Wiśniewska", other: "Wiśniewskie" },
    { male: "Sadowski", female: "Sadowska", other: "Sadowskie" },
    { male: "Borowskiskiak", female: "Borowskiskiak", other: "Borowskiskiak" },
    { male: "Wierzbickiakakskicki", female: "Wierzbickiakakskicka", other: "Wierzbickiakakskickie" },
    { male: "Bieńkowskiakcki", female: "Bieńkowskiakcka", other: "Bieńkowskiakckie" },
    { male: "Las", female: "Las", other: "Las" },
    { male: "Musiałekak", female: "Musiałekak", other: "Musiałekak" },
    { male: "Orłowski", female: "Orłowska", other: "Orłowskie" },
    { male: "Urban", female: "Urban", other: "Urban" },
    { male: "Bielawskiak", female: "Bielawskiak", other: "Bielawskiak" },
    { male: "Czarneckicki", female: "Czarneckicka", other: "Czarneckickie" },
    { male: "Cybulskiski", female: "Cybulskiska", other: "Cybulskiskie" },
    { male: "Wierzbickiakakski", female: "Wierzbickiakakska", other: "Wierzbickiakakskie" },
    { male: "Wierzbickiski", female: "Wierzbickiski", other: "Wierzbickiski" },
    { male: "Szulcckiekak", female: "Szulcckiekak", other: "Szulcckiekak" },
    { male: "Adamczykakek", female: "Adamczykakek", other: "Adamczykakek" },
    { male: "Tomaszewski", female: "Tomaszewska", other: "Tomaszewskie" },
    { male: "Lewandowskiskicki", female: "Lewandowskiskicka", other: "Lewandowskiskickie" },
    { male: "Gajewskiekek", female: "Gajewskiekek", other: "Gajewskiekek" },
    { male: "Jezioro", female: "Jezioro", other: "Jezioro" },
    { male: "Bielawskiakcki", female: "Bielawskiakcka", other: "Bielawskiakckie" },
    { male: "Stefańskiskiski", female: "Stefańskiskiska", other: "Stefańskiskiskie" },
    { male: "Góra", female: "Góra", other: "Góra" },
    { male: "Nowakcki", female: "Nowakcka", other: "Nowakckie" },
    { male: "Zającekek", female: "Zającekek", other: "Zającekek" },
    { male: "Lewandowski", female: "Lewandowska", other: "Lewandowskie" },
    { male: "Bieńkowskicki", female: "Bieńkowskicka", other: "Bieńkowskickie" },
    { male: "Wilkek", female: "Wilkek", other: "Wilkek" },
    { male: "Marcinkowskicki", female: "Marcinkowskicka", other: "Marcinkowskickie" },
    { male: "Walczakcki", female: "Walczakcka", other: "Walczakckie" },
    { male: "Błaszczykak", female: "Błaszczykak", other: "Błaszczykak" },
    { male: "Wieczorekcki", female: "Wieczorekcka", other: "Wieczorekckie" },
    { male: "Marciniakek", female: "Marciniakek", other: "Marciniakek" },
    { male: "Głowacki", female: "Głowacka", other: "Głowackie" },
    { male: "Grabowski", female: "Grabowska", other: "Grabowskie" },
    { male: "Szulccki", female: "Szulccka", other: "Szulcckie" },
    { male: "Konopackiak", female: "Konopackiak", other: "Konopackiak" },
    { male: "Bednarskicki", female: "Bednarskickiekska", other: "Bednarskickie" },
    { male: "Wilk", female: "Wilk", other: "Wilk" },
    { male: "Cybulski", female: "Cybulski", other: "Cybulski" },
    { male: "Cybulskiskicki", female: "Cybulskiskicka", other: "Cybulskiskickie" },
    { male: "Malinowski", female: "Malinowski", other: "Malinowski" },
    { male: "Gajewskickiek", female: "Gajewskickiek", other: "Gajewskickiek" },
    { male: "Jaworski", female: "Jaworska", other: "Jaworskie" },
    { male: "Kamień", female: "Kamień", other: "Kamień" },
    { male: "Adamczyk", female: "Adamczyk", other: "Adamczyk" },
    { male: "Ziółkowskickiak", female: "Ziółkowskickiak", other: "Ziółkowskickiak" },
    { male: "Szulcckiak", female: "Szulcckiak", other: "Szulcckiak" },
    { male: "Łuczakakak", female: "Łuczakakak", other: "Łuczakakak" },
    { male: "Romanowski", female: "Romanowska", other: "Romanowskie" },
    { male: "Bednarskicki", female: "Bednarskicka", other: "Bednarskickie" },
    { male: "Lewandowskiski", female: "Lewandowskiska", other: "Lewandowskiskie" },
    { male: "Malinowskiak", female: "Malinowskiak", other: "Malinowskiak" },
    { male: "Wiosna", female: "Wiosna", other: "Wiosna" },
    { male: "Gajewskicki", female: "Gajewskicka", other: "Gajewskickie" },
    { male: "Kucharski", female: "Kucharska", other: "Kucharskie" },
    { male: "Wieczorek", female: "Wieczorek", other: "Wieczorek" },
    { male: "Król", female: "Król", other: "Król" },
    { male: "Kowalski", female: "Kowalska", other: "Kowalskie" },
    { male: "Królski", female: "Królska", other: "Królskie" },
    { male: "Burza", female: "Burza", other: "Burza" },
    { male: "Topór", female: "Topór", other: "Topór" },
    { male: "Stefańskiski", female: "Stefańskiska", other: "Stefańskiskie" },
    { male: "Szulcckiek", female: "Szulcckiek", other: "Szulcckiek" },
    { male: "Baranowski", female: "Baranowska", other: "Baranowskie" },
    { male: "Łuczakckiak", female: "Łuczakckiak", other: "Łuczakckiak" },
    { male: "Grabowskicki", female: "Grabowskicka", other: "Grabowskickie" },
    { male: "Jabłońskiski", female: "Jabłońskiska", other: "Jabłońskiskie" },
    { male: "Tomczak", female: "Tomczak", other: "Tomczak" },
    { male: "Sikorski", female: "Sikorski", other: "Sikorski" },
    { male: "Malinowski", female: "Malinowski", other: "Malinowski" },
    { male: "Wiatr", female: "Wiatr", other: "Wiatr" },
    { male: "Sobczak", female: "Sobczak", other: "Sobczak" },
    { male: "Andrzejewski", female: "Andrzejewska", other: "Andrzejewskie" },
    { male: "Czarneckiak", female: "Czarneckiak", other: "Czarneckiak" },
    { male: "Słońce", female: "Słońce", other: "Słońce" },
    { male: "Skała", female: "Skała", other: "Skała" },
    { male: "Srebro", female: "Srebro", other: "Srebro" },
    { male: "Górski", female: "Górska", other: "Górskie" },
    { male: "Błaszczykcki", female: "Błaszczykcka", other: "Błaszczykckie" },
    { male: "Łuczakakakcki", female: "Łuczakakakcka", other: "Łuczakakakckie" },
    { male: "Marcinkowskiak", female: "Marcinkowskiak", other: "Marcinkowskiak" },
    { male: "Kozłowski", female: "Kozłowska", other: "Kozłowskie" },
    { male: "Ziółkowskicki", female: "Ziółkowskicka", other: "Ziółkowskickie" },
    { male: "Musiał", female: "Musiał", other: "Musiał" },
    { male: "Gajda", female: "Gajda", other: "Gajda" },
    { male: "Blask", female: "Blask", other: "Blask" },
    { male: "Łuczakakski", female: "Łuczakakska", other: "Łuczakakskie" },
    { male: "Sawicki", female: "Sawicka", other: "Sawickie" },
    { male: "Piorun", female: "Piorun", other: "Piorun" },
    { male: "Romanowskiak", female: "Romanowskiak", other: "Romanowskiak" },
    { male: "Dudek", female: "Dudek", other: "Dudek" },
    { male: "Bieńkowski", female: "Bieńkowska", other: "Bieńkowskie" },
    { male: "Kowalskicki", female: "Kowalskicka", other: "Kowalskickie" },
    { male: "Michalakski", female: "Michalakska", other: "Michalakskie" },
    { male: "Malinowskicki", female: "Malinowskicka", other: "Malinowskickie" },
    { male: "Michalskiak", female: "Michalskiak", other: "Michalskiak" },
    { male: "Mazurek", female: "Mazurek", other: "Mazurek" },
    { male: "Krawczyk", female: "Krawczyk", other: "Krawczyk" },
    { male: "Bieńkowskiak", female: "Bieńkowskiak", other: "Bieńkowskiak" },
    { male: "Piotrowski", female: "Piotrowska", other: "Piotrowskie" },
    { male: "Wróbelcki", female: "Wróbelcka", other: "Wróbelckie" },
    { male: "Złoto", female: "Złoto", other: "Złoto" },
    { male: "Wicher", female: "Wicher", other: "Wicher" },
    { male: "Trzeciak", female: "Trzeciak", other: "Trzeciak" },
    { male: "Pole", female: "Pole", other: "Pole" },
    { male: "Kaczmarekskiski", female: "Kaczmarekskiska", other: "Kaczmarekskiskie" },
    { male: "Lewandowskiski", female: "Lewandowskiski", other: "Lewandowskiski" },
    { male: "Piotrowski", female: "Piotrowski", other: "Piotrowski" },
    { male: "Michalak", female: "Michalak", other: "Michalak" },
    { male: "Bielawski", female: "Bielawska", other: "Bielawskie" },
    { male: "Stolarz", female: "Stolarz", other: "Stolarz" },
    { male: "Wasilewskickiekakekcki", female: "Wasilewskickiekakekcka", other: "Wasilewskickiekakekckie" },
    { male: "Jabłoński", female: "Jabłoński", other: "Jabłoński" },
    { male: "Sarna", female: "Sarna", other: "Sarna" },
    { male: "Kamińskiski", female: "Kamińskiska", other: "Kamińskiskie" },
    { male: "Kubiak", female: "Kubiak", other: "Kubiak" },
    { male: "Młynarz", female: "Młynarz", other: "Młynarz" },
    { male: "Morze", female: "Morze", other: "Morze" },
    { male: "Wojciechowski", female: "Wojciechowska", other: "Wojciechowskie" },
    { male: "Łuczakak", female: "Łuczakak", other: "Łuczakak" },
    { male: "Cień", female: "Cień", other: "Cień" },
    { male: "Cierń", female: "Cierń", other: "Cierń" },
    { male: "Pająk", female: "Pająk", other: "Pająk" },
    { male: "Szymański", female: "Szymańska", other: "Szymańskie" },
    { male: "Mazur", female: "Mazur", other: "Mazur" },
    { male: "Wierzbickiakakekak", female: "Wierzbickiakakekak", other: "Wierzbickiakakekak" },
    { male: "Wierzbickiakckicki", female: "Wierzbickiakckicka", other: "Wierzbickiakckickie" },
    { male: "Lato", female: "Lato", other: "Lato" },
    { male: "Błaszczyk", female: "Błaszczyk", other: "Błaszczyk" },
    { male: "Stefański", female: "Stefańska", other: "Stefańskie" },
    { male: "Janickiak", female: "Janickiak", other: "Janickiak" },
    { male: "Majewskiak", female: "Majewskiak", other: "Majewskiak" },
    { male: "Zającekckickicki", female: "Zającekckickicka", other: "Zającekckickickie" },
    { male: "Borowskiskicki", female: "Borowskiskicka", other: "Borowskiskickie" },
    { male: "Łuczakcki", female: "Łuczakcka", other: "Łuczakckie" },
    { male: "Sienkiewiczski", female: "Sienkiewiczska", other: "Sienkiewiczskie" },
    { male: "Jabłoński", female: "Jabłońska", other: "Jabłońskie" },
    { male: "Grabowskiak", female: "Grabowskiak", other: "Grabowskiak" },
    { male: "Wróbelak", female: "Wróbelak", other: "Wróbelak" },
    { male: "Wasilewskicki", female: "Wasilewskicka", other: "Wasilewskickie" },
    { male: "Bednarski", female: "Bednarska", other: "Bednarskie" },
    { male: "Brzeziński", female: "Brzeziński", other: "Brzeziński" },
    { male: "Marcinkowskiskiak", female: "Marcinkowskiskiak", other: "Marcinkowskiskiak" },
    { male: "Bednarskickiekak", female: "Bednarskickiekak", other: "Bednarskickiekak" },
    { male: "Ziółkowski", female: "Ziółkowska", other: "Ziółkowskie" },
    { male: "Kaczmarek", female: "Kaczmarekekska", other: "Kaczmareke" },
    { male: "Olejniczak", female: "Olejniczak", other: "Olejniczak" },
    { male: "Szczepański", female: "Szczepańska", other: "Szczepańskie" },
    { male: "Krawczykak", female: "Krawczykak", other: "Krawczykak" },
    { male: "Wójcikski", female: "Wójcikska", other: "Wójcikskie" },
    { male: "Lew", female: "Lew", other: "Lew" },
    { male: "Kaczmarekski", female: "Kaczmarekska", other: "Kaczmarekskie" },
    { male: "Olszewski", female: "Olszewska", other: "Olszewskie" },
    { male: "Woźniakek", female: "Woźniakek", other: "Woźniakek" },
    { male: "Woźniak", female: "Woźniak", other: "Woźniak" },
    { male: "Wierzbickiak", female: "Wierzbickiak", other: "Wierzbickiak" },
    { male: "Zającekckiski", female: "Zającekckiska", other: "Zającekckiskie" },
    { male: "Piekarz", female: "Piekarz", other: "Piekarz" },
    { male: "Sadowski", female: "Sadowski", other: "Sadowski" },
    { male: "Pawłowskiski", female: "Pawłowskiska", other: "Pawłowskiskie" },
    { male: "Gajewskickiskiek", female: "Gajewskickiskiek", other: "Gajewskickiskiek" },
    { male: "Strumień", female: "Strumień", other: "Strumień" },
    { male: "Walczakski", female: "Walczakska", other: "Walczakskie" },
    { male: "Rybak", female: "Rybak", other: "Rybak" },
    { male: "Gajewskickiski", female: "Gajewskickiski", other: "Gajewskickiski" },
    { male: "Borkowski", female: "Borkowski", other: "Borkowski" },
    { male: "Żelazo", female: "Żelazo", other: "Żelazo" },
    { male: "Szulcakcki", female: "Szulcakcka", other: "Szulcakckie" },
    { male: "Marcinkowskickiski", female: "Marcinkowskickiska", other: "Marcinkowskickiskie" },
    { male: "Gajdacki", female: "Gajdacka", other: "Gajdackie" },
    { male: "Majewskiek", female: "Majewskiek", other: "Majewskiek" },
    { male: "Marcinkowskiakcki", female: "Marcinkowskiakcka", other: "Marcinkowskiakckie" },
    { male: "Bieńkowskiskicki", female: "Bieńkowskiskicka", other: "Bieńkowskiskickie" },
    { male: "Dym", female: "Dym", other: "Dym" },
    { male: "Kruk", female: "Kruk", other: "Kruk" },
    { male: "Sikorskiskiski", female: "Sikorskiskiska", other: "Sikorskiskiskie" },
    { male: "Kamińskiski", female: "Kamińskiski", other: "Kamińskiski" },
    { male: "Adamczykcki", female: "Adamczykcka", other: "Adamczykckie" },
    { male: "Księżyc", female: "Księżyc", other: "Księżyc" },
    { male: "Urbanski", female: "Urbanska", other: "Urbanskie" },
    { male: "Gajewski", female: "Gajewska", other: "Gajewskie" },
    { male: "Sawickiakcki", female: "Sawickiakcka", other: "Sawickiakckie" },
    { male: "Bielawskiski", female: "Bielawskiska", other: "Bielawskiskie" },
    { male: "Szulc", female: "Szulc", other: "Szulc" },
    { male: "Pawłowski", female: "Pawłowska", other: "Pawłowskie" },
    { male: "Czerwiński", female: "Czerwińska", other: "Czerwińskie" },
    { male: "Majewski", female: "Majewski", other: "Majewski" },
    { male: "Czarnecki", female: "Czarnecka", other: "Czarneckie" },
    { male: "Łuczakakskiak", female: "Łuczakakskiak", other: "Łuczakakskiak" },
    { male: "Chmura", female: "Chmura", other: "Chmura" },
    { male: "Zającek", female: "Zającek", other: "Zającek" },
    { male: "Sosna", female: "Sosna", other: "Sosna" },
    { male: "Ratajczakcki", female: "Ratajczakcka", other: "Ratajczakckie" },
    { male: "Lis", female: "Lis", other: "Lis" },
    { male: "Sawickiak", female: "Sawickiak", other: "Sawickiak" },
    { male: "Wierzbickiski", female: "Wierzbickiska", other: "Wierzbickiskie" },
    { male: "Wierzbicki", female: "Wierzbicka", other: "Wierzbickie" }
];

/** @type {Array<String>} */
const MALE_NAMES = [
    "Adam",
    "Adolf",
    "Adrian",
    "Alan",
    "Albert",
    "Albin",
    "Aleks",
    "Aleksander",
    "Aleksy",
    "Alfred",
    "Alojzy",
    "Amadeusz",
    "Ambroży",
    "Anastazy",
    "Anatol",
    "Andrzej",
    "Antoni",
    "Apolinary",
    "Arek",
    "Ariel",
    "Arkadiusz",
    "Arnold",
    "Aron",
    "Artur",
    "August",
    "Augustyn",
    "Aureliusz",
    "Barnaba",
    "Bartek",
    "Bartłomiej",
    "Bartosz",
    "Bazyli",
    "Benedykt",
    "Beniamin",
    "Bernard",
    "Błażej",
    "Bogdan",
    "Bogumił",
    "Bogusław",
    "Bogusz",
    "Bohdan",
    "Bolek",
    "Bolesław",
    "Bonifacy",
    "Borys",
    "Bożydar",
    "Brajan",
    "Bratumił",
    "Bronisław",
    "Bruno",
    "Celestyn",
    "Cezary",
    "Cibor",
    "Cyprian",
    "Cyryl",
    "Czcibor",
    "Czesław",
    "Damian",
    "Daniel",
    "Darek",
    "Dariusz",
    "Dawid",
    "Dionizy",
    "Dobrogost",
    "Dobromił",
    "Dobrosław",
    "Dominik",
    "Donat",
    "Dorian",
    "Dymitr",
    "Edmund",
    "Edward",
    "Eliasz",
    "Eligiusz",
    "Emil",
    "Emilian",
    "Ernest",
    "Erwin",
    "Eryk",
    "Eugeniusz",
    "Eustachy",
    "Fabian",
    "Felicjan",
    "Feliks",
    "Ferdynand",
    "Filip",
    "Florian",
    "Franciszek",
    "Fryderyk",
    "Gabriel",
    "Gaweł",
    "Gerard",
    "Gerwazy",
    "Gniewko",
    "Gniewomir",
    "Gracjan",
    "Grzegorz",
    "Gustaw",
    "Henryk",
    "Hiacynt",
    "Hieronim",
    "Hipolit",
    "Hubert",
    "Ignacy",
    "Igor",
    "Irek",
    "Ireneusz",
    "Iwan",
    "Iwo",
    "Izaak",
    "Izydor",
    "Jacek",
    "Jacenty",
    "Jakub",
    "Jan",
    "Janek",
    "Janusz",
    "Jarek",
    "Jarogniew",
    "Jaromir",
    "Jaropełk",
    "Jarosław",
    "Jędrzej",
    "Jeremi",
    "Jeremiasz",
    "Jerzy",
    "Joachim",
    "Jonasz",
    "Jonatan",
    "Jozafat",
    "Józef",
    "Julek",
    "Julian",
    "Juliusz",
    "Jurek",
    "Justyn",
    "Kacper",
    "Kajetan",
    "Kamil",
    "Karol",
    "Kasjan",
    "Kazik",
    "Kazimierz",
    "Kewin",
    "Klaudiusz",
    "Klemens",
    "Kondrat",
    "Konrad",
    "Konstanty",
    "Konstantyn",
    "Kordian",
    "Kornel",
    "Korneliusz",
    "Kosma",
    "Kryspin",
    "Krystian",
    "Krystyn",
    "Krzesimir",
    "Krzyś",
    "Krzysiek",
    "Krzysztof",
    "Ksawery",
    "Kuba",
    "Lech",
    "Lechosław",
    "Leon",
    "Leonard",
    "Leopold",
    "Lesław",
    "Leszek",
    "Lew",
    "Longin",
    "Lubomierz",
    "Łucjan",
    "Lucjan",
    "Lucjusz",
    "Ludwik",
    "Łukasz",
    "Maciej",
    "Madej",
    "Maks",
    "Maksym",
    "Maksymilian",
    "Manfred",
    "Marcel",
    "Marceli",
    "Marcin",
    "Marek",
    "Maria",
    "Marian",
    "Mariusz",
    "Mateusz",
    "Maurycy",
    "Metody",
    "Michał",
    "Mieczysław",
    "Mieszko",
    "Mikołaj",
    "Miłogost",
    "Miłosław",
    "Miłosz",
    "Mirek",
    "Miron",
    "Mirosław",
    "Mścisław",
    "Narcyz",
    "Natan",
    "Nikodem",
    "Norbert",
    "Oktawian",
    "Oktawiusz",
    "Olaf",
    "Olek",
    "Olgierd",
    "Oliwer",
    "Oliwier",
    "Oskar",
    "Patryk",
    "Paweł",
    "Piotr",
    "Przemek",
    "Przemko",
    "Przemo",
    "Przemysł",
    "Przemysław",
    "Radek",
    "Radomił",
    "Radosław",
    "Radzim",
    "Rafał",
    "Rajmund",
    "Remigiusz",
    "Robert",
    "Roch",
    "Roland",
    "Roman",
    "Romuald",
    "Ryszard",
    "Samuel",
    "Sebastian",
    "Serafin",
    "Sergiusz",
    "Seweryn",
    "Sławomir",
    "Sobiesław",
    "Stan",
    "Stanisław",
    "Stefan",
    "Stefek",
    "Sulisław",
    "Świętopełk",
    "Świętosław",
    "Sylwester",
    "Szczepan",
    "Szczęsny",
    "Szymon",
    "Tadeusz",
    "Teodor",
    "Teofil",
    "Tobiasz",
    "Tomasz",
    "Tomek",
    "Tycjan",
    "Tymek",
    "Tymon",
    "Tymoteusz",
    "Tytus",
    "Urban",
    "Uriasz",
    "Wacław",
    "Waldek",
    "Waldemar",
    "Walenty",
    "Walerian",
    "Walery",
    "Walter",
    "Warcisław",
    "Wawrzyniec",
    "Więcesław",
    "Wielisław",
    "Wiesław",
    "Wiktor",
    "Wilhelm",
    "Wincenty",
    "Wisław",
    "Wit",
    "Witek",
    "Witołd",
    "Witold",
    "Witosław",
    "Władek",
    "Władysław",
    "Włodek",
    "Włodzimierz",
    "Włodzisław",
    "Wojciech",
    "Wojsław",
    "Wojtek",
    "Zachariasz",
    "Zawisza",
    "Zbigniew",
    "Zdzisław",
    "Zenon",
    "Ziemowit",
    "Zygfryd",
    "Zygmunt"
];

/** @type {Array<String>} */
const FEMALE_NAMES = [
    "Ada",
    "Adela",
    "Adelajda",
    "Adriana",
    "Adrianna",
    "Agata",
    "Agatka",
    "Agnieszka",
    "Albina",
    "Aldona",
    "Aleksandra",
    "Alfreda",
    "Alicja",
    "Alina",
    "Amelia",
    "Anastazja",
    "Andżelika",
    "Aneta",
    "Angelika",
    "Ania",
    "Aniela",
    "Anielka",
    "Anika",
    "Anita",
    "Anka",
    "Anna",
    "Antonina",
    "Apolonia",
    "Ariadna",
    "Asia",
    "Augustyna",
    "Aurelia",
    "Balbina",
    "Barbara",
    "Basia",
    "Beata",
    "Beatrycze",
    "Benedykta",
    "Berenika",
    "Bernadeta",
    "Bernadetta",
    "Berta",
    "Bianka",
    "Blanka",
    "Bogdana",
    "Bogna",
    "Bogumiła",
    "Bogusława",
    "Bolesława",
    "Bożena",
    "Bronisława",
    "Brygida",
    "Cecylia",
    "Celestyna",
    "Celina",
    "Czesława",
    "Dagmara",
    "Daniela",
    "Danka",
    "Danuta",
    "Daria",
    "Diana",
    "Dobromiła",
    "Dobrosława",
    "Dominika",
    "Donata",
    "Dorota",
    "Dosia",
    "Dżesika",
    "Edyta",
    "Ela",
    "Eleonora",
    "Eligia",
    "Eliza",
    "Elwira",
    "Elżbieta",
    "Emilia",
    "Eryka",
    "Estera",
    "Eugenia",
    "Eulalia",
    "Eunika",
    "Ewa",
    "Ewelina",
    "Faustyna",
    "Felicja",
    "Felicyta",
    "Filipina",
    "Florentyna",
    "Franciszka",
    "Fryderyka",
    "Gabriela",
    "Gaja",
    "Genowefa",
    "Gertruda",
    "Gosia",
    "Gracja",
    "Gracjana",
    "Grażyna",
    "Greta",
    "Halina",
    "Halinka",
    "Hania",
    "Hanna",
    "Helena",
    "Helenka",
    "Henryka",
    "Hiacynta",
    "Honorata",
    "Ida",
    "Idalia",
    "Iga",
    "Ignacja",
    "Ilona",
    "Inga",
    "Irena",
    "Irenka",
    "Irmina",
    "Iwona",
    "Iza",
    "Izabela",
    "Izabella",
    "Izolda",
    "Jadwiga",
    "Jadzia",
    "Jaga",
    "Jagienka",
    "Jagna",
    "Jagoda",
    "Jagusia",
    "Janina",
    "Janka",
    "Jarosława",
    "Jaśmina",
    "Joanna",
    "Joasia",
    "Jola",
    "Jolanta",
    "Jowita",
    "Józefa",
    "Józefina",
    "Judyta",
    "Julia",
    "Julianna",
    "Julita",
    "Justyna",
    "Kaja",
    "Kalina",
    "Kamila",
    "Kamilla",
    "Karina",
    "Karola",
    "Karolina",
    "Kasandra",
    "Kasia",
    "Katarzyna",
    "Kazia",
    "Kazimiera",
    "Kinga",
    "Klara",
    "Klaudia",
    "Klementyna",
    "Klotylda",
    "Konstancja",
    "Kornelia",
    "Krysia",
    "Krystiana",
    "Krystyna",
    "Krzysztofa",
    "Ksenia",
    "Kunegunda",
    "Larysa",
    "Laura",
    "Lechosława",
    "Lena",
    "Leokadia",
    "Lesława",
    "Letycja",
    "Lidia",
    "Lidka",
    "Lilia",
    "Liliana",
    "Lilianna",
    "Liwia",
    "Longina",
    "Łucja",
    "Lucyna",
    "Ludmiła",
    "Ludwika",
    "Luiza",
    "Magda",
    "Magdalena",
    "Maja",
    "Maja",
    "Małgorzata",
    "Małgosia",
    "Malina",
    "Malwina",
    "Marcela",
    "Marcelina",
    "Marcjanna",
    "Maria",
    "Marianna",
    "Marietta",
    "Marika",
    "Mariola",
    "Marlena",
    "Marta",
    "Martyna",
    "Maryla",
    "Maryna",
    "Marysia",
    "Marzanna",
    "Marzena",
    "Matylda",
    "Melania",
    "Michalina",
    "Mieczysława",
    "Milena",
    "Milka",
    "Mira",
    "Miriam",
    "Mirka",
    "Mirosława",
    "Monika",
    "Nadia",
    "Nadzieja",
    "Natalia",
    "Natalka",
    "Natasza",
    "Nela",
    "Nikola",
    "Nina",
    "Noemi",
    "Oktawia",
    "Ola",
    "Olga",
    "Olimpia",
    "Oliwia",
    "Otylia",
    "Pati",
    "Patka",
    "Patrycja",
    "Paula",
    "Paulina",
    "Pelagia",
    "Pola",
    "Radomiła",
    "Radosława",
    "Regina",
    "Renata",
    "Renia",
    "Roksana",
    "Romana",
    "Romualda",
    "Róża",
    "Rozalia",
    "Ruta",
    "Sabina",
    "Salomea",
    "Samanta",
    "Sandra",
    "Sara",
    "Seweryna",
    "Sława",
    "Sławomira",
    "Sobiesława",
    "Sonia",
    "Stanisława",
    "Stasia",
    "Stefania",
    "Stefcia",
    "Sybilla",
    "Sylwia",
    "Tamara",
    "Tatiana",
    "Tekla",
    "Teodora",
    "Teodozja",
    "Teofila",
    "Teresa",
    "Tola",
    "Tosia",
    "Ula",
    "Urszula",
    "Wacława",
    "Walentyna",
    "Waleria",
    "Wanda",
    "Wanesa",
    "Wanessa",
    "Wera",
    "Weronika",
    "Wiera",
    "Wiesława",
    "Wiktoria",
    "Wiola",
    "Wioleta",
    "Wioletta",
    "Wisława",
    "Władysława",
    "Wojciecha",
    "Żaklina",
    "Żaneta",
    "Zdzisława",
    "Zofia",
    "Zoja",
    "Zosia",
    "Zula",
    "Zuza",
    "Zuzanna",
    "Zuzia",
    "Zyta"
];

/** @type {Array<String>} */
const OTHER_NAMES = [
    'Alex',
    'Maria',
    'Iwo',
    'Nico'
];

export {LASTNAMES, MALE_NAMES, FEMALE_NAMES, OTHER_NAMES};