/** 
 * @typedef {Object} LASTNAME_DATA
 * @param {String} male
 * @param {String} female
 * @param {String} other
 */

const LASTNAMES = [
    { male: "Dudekcki", female: "Dudekcka", other: "Dudekckie" },
    { male: "Rzeka", female: "Rzeka", other: "Rzeka" },
    { male: "Zima", female: "Zima", other: "Zima" },
    { male: "Wieczor", female: "Wieczor", other: "Wieczor" },
    { male: "Zając", female: "Zając", other: "Zając" },
    { male: "Urbanek", female: "Urbanek", other: "Urbanek" },
    { male: "Zawadzki", female: "Zawadzka", other: "Zawadzkie" },
    { male: "Marcinkowski", female: "Marcinkowska", other: "Marcinkowskie" },
    { male: "Malinowski", female: "Malinowska", other: "Malinowskie" },
    { male: "Musiałek", female: "Musiałek", other: "Musiałek" },
    { male: "Kołodziejski", female: "Kołodziejska", other: "Kołodziejskie" },
    { male: "Dąbrowski", female: "Dąbrowska", other: "Dąbrowskie" },
    { male: "Lewandowski", female: "Lewandowski", other: "Lewandowski" },
    { male: "Walczak", female: "Walczak", other: "Walczak" },
    { male: "Grabowski", female: "Grabowska", other: "Grabowskie" },
    { male: "Jankowski", female: "Jankowska", other: "Jankowskie" },
    { male: "Gwiazda", female: "Gwiazda", other: "Gwiazda" },
    { male: "Majewski", female: "Majewska", other: "Majewskie" },
    { male: "Gajewski", female: "Gajewska", other: "Gajewskie" },
    { male: "Nowicki", female: "Nowicka", other: "Nowickie" },
    { male: "Brzoza", female: "Brzoza", other: "Brzoza" },
    { male: "Kucharski", female: "Kucharska", other: "Kucharskie" },
    { male: "Miedź", female: "Miedź", other: "Miedź" },
    { male: "Jesień", female: "Jesień", other: "Jesień" },
    { male: "Lisicki", female: "Lisicka", other: "Lisickie" },
    { male: "Makowski", female: "Makowska", other: "Makowskie" },
    { male: "Łuczarski", female: "Łuczarska", other: "Łuczarskie" },
    { male: "Piasek", female: "Piasek", other: "Piasek" },
    { male: "Grom", female: "Grom", other: "Grom" },
    { male: "Wróbel", female: "Wróbel", other: "Wróbel" },
    { male: "Orzeł", female: "Orzeł", other: "Orzeł" },
    { male: "Kowal", female: "Kowal", other: "Kowal" },
    { male: "Brzeziński", female: "Brzezińska", other: "Brzezińskie" },
    { male: "Marciniak", female: "Marciniak", other: "Marciniak" },
    { male: "Stanicki", female: "Stanicka", other: "Stanickie" },
    { male: "Wasilewski", female: "Wasilewska", other: "Wasilewskie" },
    { male: "Mróz", female: "Mróz", other: "Mróz" },
    { male: "Dąb", female: "Dąb", other: "Dąb" },
    { male: "Dąbrowa", female: "Dąbrowa", other: "Dąbrowa" },
    { male: "Bąk", female: "Bąk", other: "Bąk" },
    { male: "Borowski", female: "Borowska", other: "Borowskie" },
    { male: "Kaczmarek", female: "Kaczmarek", other: "Kaczmarek" },
    { male: "Ratajczak", female: "Ratajczak", other: "Ratajczak" },
    { male: "Gajdacki", female: "Gajdacka", other: "Gajdackie" },
    { male: "Łuczak", female: "Łuczak", other: "Łuczak" },
    { male: "Zieliński", female: "Zielińska", other: "Zielińskie" },
    { male: "Popiół", female: "Popiół", other: "Popiół" },
    { male: "Szabla", female: "Szabla", other: "Szabla" },
    { male: "Rów", female: "Rów", other: "Rów" },
    { male: "Tomaszewski", female: "Tomaszewski", other: "Tomaszewski" },
    { male: "Lewandowski", female: "Lewandowski", other: "Lewandowski" },
    { male: "Michalski", female: "Michalska", other: "Michalskie" },
    { male: "Łąka", female: "Łąka", other: "Łąka" },
    { male: "Chojnacki", female: "Chojnacka", other: "Chojnackie" },
    { male: "Wiśniewski", female: "Wiśniewska", other: "Wiśniewskie" },
    { male: "Sadowski", female: "Sadowska", other: "Sadowskie" },
    { male: "Las", female: "Las", other: "Las" },
    { male: "Orłowski", female: "Orłowska", other: "Orłowskie" },
    { male: "Urban", female: "Urban", other: "Urban" },
    { male: "Jezioro", female: "Jezioro", other: "Jezioro" },
    { male: "Góra", female: "Góra", other: "Góra" },
    { male: "Nowacki", female: "Nowacka", other: "Nowackie" },
    { male: "Wilczek", female: "Wilczek", other: "Wilczek" },
    { male: "Błaszczyk", female: "Błaszczyk", other: "Błaszczyk" },
    { male: "Głowacki", female: "Głowacka", other: "Głowackie" },
    { male: "Szulski", female: "Szulska", other: "Szulskie" },
    { male: "Konopnicki", female: "Konopnicka", other: "Konopnickie" },
    { male: "Wilk", female: "Wilk", other: "Wilk" },
    { male: "Cybulski", female: "Cybulska", other: "Cybulskie" },
    { male: "Jaworski", female: "Jaworska", other: "Jaworskie" },
    { male: "Kamień", female: "Kamień", other: "Kamień" },
    { male: "Adamczyk", female: "Adamczyk", other: "Adamczyk" },
    { male: "Romanowski", female: "Romanowska", other: "Romanowskie" },
    { male: "Wiosna", female: "Wiosna", other: "Wiosna" },
    { male: "Wieczorek", female: "Wieczorek", other: "Wieczorek" },
    { male: "Król", female: "Król", other: "Król" },
    { male: "Kowalski", female: "Kowalska", other: "Kowalskie" },
    { male: "Królski", female: "Królska", other: "Królskie" },
    { male: "Burza", female: "Burza", other: "Burza" },
    { male: "Topór", female: "Topór", other: "Topór" },
    { male: "Baranowski", female: "Baranowska", other: "Baranowskie" },
    { male: "Tomczak", female: "Tomczak", other: "Tomczak" },
    { male: "Sikorski", female: "Sikorska", other: "Sikorskie" },
    { male: "Wiatr", female: "Wiatr", other: "Wiatr" },
    { male: "Sobczak", female: "Sobczak", other: "Sobczak" },
    { male: "Andrzejewski", female: "Andrzejewska", other: "Andrzejewskie" },
    { male: "Słońce", female: "Słońce", other: "Słońce" },
    { male: "Skała", female: "Skała", other: "Skała" },
    { male: "Srebro", female: "Srebro", other: "Srebro" },
    { male: "Górski", female: "Górska", other: "Górskie" },
    { male: "Kozłowski", female: "Kozłowska", other: "Kozłowskie" },
    { male: "Musiał", female: "Musiał", other: "Musiał" },
    { male: "Gajda", female: "Gajda", other: "Gajda" },
    { male: "Blask", female: "Blask", other: "Blask" },
    { male: "Sawicki", female: "Sawicka", other: "Sawickie" },
    { male: "Piorun", female: "Piorun", other: "Piorun" },
    { male: "Dudek", female: "Dudek", other: "Dudek" },
    { male: "Bieńkowski", female: "Bieńkowska", other: "Bieńkowskie" },
    { male: "Mazurek", female: "Mazurek", other: "Mazurek" },
    { male: "Krawczyk", female: "Krawczyk", other: "Krawczyk" },
    { male: "Piotrowski", female: "Piotrowska", other: "Piotrowskie" },
    { male: "Wróblecki", female: "Wróblecka", other: "Wróbleckie" },
    { male: "Złoto", female: "Złoto", other: "Złoto" },
    { male: "Wicher", female: "Wicher", other: "Wicher" },
    { male: "Trzeciak", female: "Trzeciak", other: "Trzeciak" },
    { male: "Pole", female: "Pole", other: "Pole" },
    { male: "Kaczmarski", female: "Kaczmarska", other: "Kaczmarskie" },
    { male: "Michalak", female: "Michalak", other: "Michalak" },
    { male: "Bielawski", female: "Bielawska", other: "Bielawskie" },
    { male: "Stolarz", female: "Stolarz", other: "Stolarz" },
    { male: "Sarna", female: "Sarna", other: "Sarna" },
    { male: "Kamiński", female: "Kamińska", other: "Kamińskie" },
    { male: "Kubiak", female: "Kubiak", other: "Kubiak" },
    { male: "Młynarz", female: "Młynarz", other: "Młynarz" },
    { male: "Morze", female: "Morze", other: "Morze" },
    { male: "Wojciechowski", female: "Wojciechowska", other: "Wojciechowskie" },
    { male: "Cień", female: "Cień", other: "Cień" },
    { male: "Cierń", female: "Cierń", other: "Cierń" },
    { male: "Pająk", female: "Pająk", other: "Pająk" },
    { male: "Szymański", female: "Szymańska", other: "Szymańskie" },
    { male: "Mazur", female: "Mazur", other: "Mazur" },
    { male: "Lato", female: "Lato", other: "Lato" },
    { male: "Stefański", female: "Stefańska", other: "Stefańskie" },
    { male: "Janickiak", female: "Janickiak", other: "Janickiak" },
    { male: "Majewskiak", female: "Majewskiak", other: "Majewskiak" },
    { male: "Zajączewski", female: "Zajączewska", other: "Zajączewskie" },
    { male: "Sienkiewicz", female: "Sienkiewicz", other: "Sienkiewicz" },
    { male: "Jabłoński", female: "Jabłońska", other: "Jabłońskie" },
    { male: "Wróbelak", female: "Wróbelak", other: "Wróbelak" },
    { male: "Bednarski", female: "Bednarska", other: "Bednarskie" },
    { male: "Ziółkowski", female: "Ziółkowska", other: "Ziółkowskie" },
    { male: "Olejniczak", female: "Olejniczak", other: "Olejniczak" },
    { male: "Szczepański", female: "Szczepańska", other: "Szczepańskie" },
    { male: "Wójcik", female: "Wójcik", other: "Wójcik" },
    { male: "Lew", female: "Lew", other: "Lew" },
    { male: "Olszewski", female: "Olszewska", other: "Olszewskie" },
    { male: "Woźniak", female: "Woźniak", other: "Woźniak" },
    { male: "Piekarz", female: "Piekarz", other: "Piekarz" },
    { male: "Strumień", female: "Strumień", other: "Strumień" },
    { male: "Rybak", female: "Rybak", other: "Rybak" },
    { male: "Borkowski", female: "Borkowski", other: "Borkowski" },
    { male: "Żelazo", female: "Żelazo", other: "Żelazo" },
    { male: "Dym", female: "Dym", other: "Dym" },
    { male: "Kruk", female: "Kruk", other: "Kruk" },
    { male: "Księżyc", female: "Księżyc", other: "Księżyc" },
    { male: "Urbanski", female: "Urbanska", other: "Urbanskie" },
    { male: "Szulc", female: "Szulc", other: "Szulc" },
    { male: "Pawłowski", female: "Pawłowska", other: "Pawłowskie" },
    { male: "Czerwiński", female: "Czerwińska", other: "Czerwińskie" },
    { male: "Majewski", female: "Majewski", other: "Majewski" },
    { male: "Czarnecki", female: "Czarnecka", other: "Czarneckie" },
    { male: "Łuczarz", female: "Łuczarz", other: "Łuczarz" },
    { male: "Chmura", female: "Chmura", other: "Chmura" },
    { male: "Zajączek", female: "Zajączek", other: "Zajączek" },
    { male: "Sosna", female: "Sosna", other: "Sosna" },
    { male: "Lis", female: "Lis", other: "Lis" },
    { male: "Wierzbicki", female: "Wierzbicka", other: "Wierzbickie" },
    { male: "Flet", female: "Flet", other: "Flet" },
    { male: "Sikora", female: "Sikora", other: "Sikora" },
    { male: "Grzebień", female: "Grzebień", other: "Grzebień" },
    { male: "Gołębiowski", female: "Gołębiowska", other: "Gołębiowskie" },
    { male: "Szaniecki", female: "Szaniecka", other: "Szanieckie" },
    { male: "Szaniec", female: "Szaniec", other: "Szaniec" },
    { male: "Goniec", female: "Goniec", other: "Goniec" },
    { male: "Hetman", female: "Hetman", other: "Hetman" },
    { male: "Szmyt", female: "Szmyt", other: "Szmyt" },
    { male: "Koń", female: "Koń", other: "Koń" },
    { male: "Szkapa", female: "Szkapa", other: "Szkapa" },
    { male: "Okoń", female: "Okoń", other: "Okoń" },
    { male: "Koński", female: "Końska", other: "Końskie" },
    { male: "Okoński", female: "Okońska", other: "Okońskie" },
    { male: "Pion", female: "Pion", other: "Pion" },
    { male: "Grajek", female: "Grajek", other: "Grajek"},
    { male: "Adamski", female: "Adamska", other: "Adamskie"},
    { male: "Jakubowski", female: "Jakubowska", other: "Jakubowskie"},
    { male: "Pręt", female: "Pręt", other: "Pręt"},
    { male: "Drągal", female: "Drągal", other: "Drągal"},
    { male: "Drągalski", female: "Drągalska", other: "Drągalskie"},
    { male: "Puszczyk", female: "Puszczyk", other: "Puszczyk"},
    { male: "Puchacz", female: "Puchacz", other: "Puchacz"},
    { male: "Gruchacz", female: "Gruchacz", other: "Gruchacz"},
    { male: "Kot", female: "Kot", other: "Kot"},
    { male: "Kejter", female: "Kejter", other: "Kejter"},
    { male: "Por", female: "Por", other: "Por"},
    { male: "Ziemiański", female: "Ziemiańska", other: "Ziemiańskie"},
    { male: "Nielot", female: "Nielot", other: "Nielot"},
    { male: "Ptak", female: "Ptak", other: "Ptak"},
    { male: "Piwowar", female: "Piwowar", other: "Piwowar"},
    { male: "Winiak", female: "Winiak", other: "Winiak"},
    { male: "Marchwiński", female: "Marchwińska", other: "Marchwińskie"},
    { male: "Borek", female: "Borek", other: "Borek"},
    { male: "Worek", female: "Worek", other: "Worek"},
    { male: "Korek", female: "Korek", other: "Korek"},
    { male: "Gała", female: "Gała", other: "Gała"},
    { male: "Gałka", female: "Gałka", other: "Gałka"},
    { male: "Gałczyński", female: "Gałczyńska", other: "Gałczyńske"},
    { male: "Gałecki", female: "Gałecka", other: "Gałeckie"},
    { male: "Sobota", female: "Sobota", other: "Sobota"},
    { male: "Okap", female: "Okap", other: "Okap"},
    { male: "Kropla", female: "Kropla", other: "Kropla"},
    { male: "Noga", female: "Noga", other: "Noga"},
    { male: "Szkit", female: "Szkit", other: "Szkit"},
    { male: "Szkutnik", female: "Szkutnik", other: "Szkutnik"},
    { male: "Tucznik", female: "Tucznik", other: "Tucznik"},
    { male: "Tuńczyk", female: "Tuńczyk", other: "Tuńczyk"},
    { male: "Kopyto", female: "Kopyto", other: "Kopyto"},
    { male: "Podkowa", female: "Podkowa", other: "Podkowa"},
    { male: "Brama", female: "Brama", other: "Brama"},
    { male: "Tama", female: "Tama", other: "Tama"},
    { male: "Pietrycha", female: "Pietrycha", other: "Pietrycha"},
    { male: "Orzech", female: "Orzech", other: "Orzech"},
    { male: "Ślimak", female: "Ślimak", other: "Ślimak"},
    { male: "Orzechowski", female: "Orzechowska", other: "Orzechowskie"},
    { male: "Rozeń", female: "Rozeń", other: "Rozeń"},
    { male: "Gibek", female: "Gibek", other: "Gibek"},
    { male: "Trufel", female: "Trufel", other: "Trufel"},
    { male: "Grzyb", female: "Grzyb", other: "Grzyb"},
    { male: "Grzybek", female: "Grzybek", other: "Grzybek"},
    { male: "Grzybowski", female: "Grzybowska", other: "Grzybowskie"},
    { male: "Pieczarka", female: "Pieczarka", other: "Pieczarka"},
    { male: "Pieczarski", female: "Pieczarska", other: "Pieczarskie"},
    { male: "Tłok", female: "Tłok", other: "Tłok"},
    { male: "Komin", female: "Komin", other: "Komin"},
    { male: "Kula", female: "Kula", other: "Kula"},
    { male: "Gips", female: "Gips", other: "Gips"},
    { male: "Żeton", female: "Żeton", other: "Żeton"},
    { male: "Żądło", female: "Żądło", other: "Żądło"},
    { male: "Mucha", female: "Mucha", other: "Mucha"},
    { male: "Robak", female: "Robak", other: "Robak"},
    { male: "Robaczek", female: "Robaczek", other: "Robaczek"},
    { male: "Robakowski", female: "Robakowska", other: "Robakowske"},
    { male: "Skrzypek", female: "Skrzypek", other: "Skrzypek"},
    { male: "Drachal", female: "Drachal", other: "Drachal"},
    { male: "Skrzypczak", female: "Skrzypczak", other: "Skrzypczak"},
    { male: "Mikołajczak", female: "Mikołajczak", other: "Mikołajczak"},
    { male: "Totem", female: "Totem", other: "Totem"},
    { male: "Golem", female: "Golem", other: "Golem"},
    { male: "Golemiec", female: "Golemiec", other: "Golemiec"},
    { male: "Golec", female: "Golec", other: "Golec"},
    { male: "Wilczarz", female: "Wilczarz", other: "Wilczarz"},
    { male: "Srogi", female: "Sroga", other: "Srogie"},
    { male: "Pchła", female: "Pchła", other: "Pchła"},
    { male: "Mąka", female: "Mąka", other: "Mąka"},
    { male: "Mąkowski", female: "Mąkowska", other: "Mąkowskie"},
    { male: "Młynarczyk", female: "Młynarczyk", other: "Młynarczyk"},
    { male: "Mokry", female: "Mokra", other: "Mokre"},
    { male: "Bolec", female: "Bolec", other: "Bolec"},
    { male: "Bolek", female: "Bolek", other: "Bolek"},
    { male: "Bolczyk", female: "Bolczyk", other: "Bolczyk"},
    { male: "Koral", female: "Koral", other: "Koral"}
];

/** @type {Array<String>} */
const MALE_NAMES = [
    "Adam",
    "Adolf",
    "Adrian",
    "Alan",
    "Albert",
    "Albin",
    "Aleks",
    "Aleksander",
    "Aleksy",
    "Alfred",
    "Alojzy",
    "Amadeusz",
    "Ambroży",
    "Anastazy",
    "Anatol",
    "Andrzej",
    "Antoni",
    "Apolinary",
    "Arek",
    "Ariel",
    "Arkadiusz",
    "Arnold",
    "Aron",
    "Artur",
    "August",
    "Augustyn",
    "Aureliusz",
    "Barnaba",
    "Bartek",
    "Bartłomiej",
    "Bartosz",
    "Bazyli",
    "Benedykt",
    "Beniamin",
    "Bernard",
    "Błażej",
    "Bogdan",
    "Bogumił",
    "Bogusław",
    "Bogusz",
    "Bohdan",
    "Bolek",
    "Bolesław",
    "Bonifacy",
    "Borys",
    "Bożydar",
    "Brajan",
    "Bratumił",
    "Bronisław",
    "Bruno",
    "Celestyn",
    "Cezary",
    "Cibor",
    "Cyprian",
    "Cyryl",
    "Czcibor",
    "Czesław",
    "Damian",
    "Daniel",
    "Darek",
    "Dariusz",
    "Dawid",
    "Dionizy",
    "Dobrogost",
    "Dobromił",
    "Dobrosław",
    "Dominik",
    "Donat",
    "Dorian",
    "Dymitr",
    "Edmund",
    "Edward",
    "Eliasz",
    "Eligiusz",
    "Emil",
    "Emilian",
    "Ernest",
    "Erwin",
    "Eryk",
    "Eugeniusz",
    "Eustachy",
    "Fabian",
    "Felicjan",
    "Feliks",
    "Ferdynand",
    "Filip",
    "Florian",
    "Franciszek",
    "Fryderyk",
    "Gabriel",
    "Gaweł",
    "Gerard",
    "Gerwazy",
    "Gniewko",
    "Gniewomir",
    "Gracjan",
    "Grzegorz",
    "Gustaw",
    "Henryk",
    "Hiacynt",
    "Hieronim",
    "Hipolit",
    "Hubert",
    "Ignacy",
    "Igor",
    "Irek",
    "Ireneusz",
    "Iwan",
    "Iwo",
    "Izaak",
    "Izydor",
    "Jacek",
    "Jacenty",
    "Jakub",
    "Jan",
    "Janek",
    "Janusz",
    "Jarek",
    "Jarogniew",
    "Jaromir",
    "Jaropełk",
    "Jarosław",
    "Jędrzej",
    "Jeremi",
    "Jeremiasz",
    "Jerzy",
    "Joachim",
    "Jonasz",
    "Jonatan",
    "Jozafat",
    "Józef",
    "Julek",
    "Julian",
    "Juliusz",
    "Jurek",
    "Justyn",
    "Kacper",
    "Kajetan",
    "Kamil",
    "Karol",
    "Kasjan",
    "Kazik",
    "Kazimierz",
    "Kewin",
    "Klaudiusz",
    "Klemens",
    "Kondrat",
    "Konrad",
    "Konstanty",
    "Konstantyn",
    "Kordian",
    "Kornel",
    "Korneliusz",
    "Kosma",
    "Kryspin",
    "Krystian",
    "Krystyn",
    "Krzesimir",
    "Krzyś",
    "Krzysiek",
    "Krzysztof",
    "Ksawery",
    "Kuba",
    "Lech",
    "Lechosław",
    "Leon",
    "Leonard",
    "Leopold",
    "Lesław",
    "Leszek",
    "Lew",
    "Longin",
    "Lubomierz",
    "Łucjan",
    "Lucjan",
    "Lucjusz",
    "Ludwik",
    "Łukasz",
    "Maciej",
    "Madej",
    "Maks",
    "Maksym",
    "Maksymilian",
    "Manfred",
    "Marcel",
    "Marceli",
    "Marcin",
    "Marek",
    "Maria",
    "Marian",
    "Mariusz",
    "Mateusz",
    "Maurycy",
    "Metody",
    "Michał",
    "Mieczysław",
    "Mieszko",
    "Mikołaj",
    "Miłogost",
    "Miłosław",
    "Miłosz",
    "Mirek",
    "Miron",
    "Mirosław",
    "Mścisław",
    "Narcyz",
    "Natan",
    "Nikodem",
    "Norbert",
    "Oktawian",
    "Oktawiusz",
    "Olaf",
    "Olek",
    "Olgierd",
    "Oliwer",
    "Oliwier",
    "Oskar",
    "Patryk",
    "Paweł",
    "Piotr",
    "Przemek",
    "Przemko",
    "Przemo",
    "Przemysł",
    "Przemysław",
    "Radek",
    "Radomił",
    "Radosław",
    "Radzim",
    "Rafał",
    "Rajmund",
    "Remigiusz",
    "Robert",
    "Roch",
    "Roland",
    "Roman",
    "Romuald",
    "Ryszard",
    "Samuel",
    "Sebastian",
    "Serafin",
    "Sergiusz",
    "Seweryn",
    "Sławomir",
    "Sobiesław",
    "Stan",
    "Stanisław",
    "Stefan",
    "Stefek",
    "Sulisław",
    "Świętopełk",
    "Świętosław",
    "Sylwester",
    "Szczepan",
    "Szczęsny",
    "Szymon",
    "Tadeusz",
    "Teodor",
    "Teofil",
    "Tobiasz",
    "Tomasz",
    "Tomek",
    "Tycjan",
    "Tymek",
    "Tymon",
    "Tymoteusz",
    "Tytus",
    "Urban",
    "Uriasz",
    "Wacław",
    "Waldek",
    "Waldemar",
    "Walenty",
    "Walerian",
    "Walery",
    "Walter",
    "Warcisław",
    "Wawrzyniec",
    "Więcesław",
    "Wielisław",
    "Wiesław",
    "Wiktor",
    "Wilhelm",
    "Wincenty",
    "Wisław",
    "Wit",
    "Witek",
    "Witołd",
    "Witold",
    "Witosław",
    "Władek",
    "Władysław",
    "Włodek",
    "Włodzimierz",
    "Włodzisław",
    "Wojciech",
    "Wojsław",
    "Wojtek",
    "Zachariasz",
    "Zawisza",
    "Zbigniew",
    "Zdzisław",
    "Zenon",
    "Ziemowit",
    "Zygfryd",
    "Zygmunt"
];

/** @type {Array<String>} */
const FEMALE_NAMES = [
    "Ada",
    "Adela",
    "Adelajda",
    "Adriana",
    "Adrianna",
    "Agata",
    "Agatka",
    "Agnieszka",
    "Albina",
    "Aldona",
    "Aleksandra",
    "Alfreda",
    "Alicja",
    "Alina",
    "Amelia",
    "Anastazja",
    "Andżelika",
    "Aneta",
    "Angelika",
    "Ania",
    "Aniela",
    "Anielka",
    "Anika",
    "Anita",
    "Anka",
    "Anna",
    "Antonina",
    "Apolonia",
    "Ariadna",
    "Asia",
    "Augustyna",
    "Aurelia",
    "Balbina",
    "Barbara",
    "Basia",
    "Beata",
    "Beatrycze",
    "Benedykta",
    "Berenika",
    "Bernadeta",
    "Bernadetta",
    "Berta",
    "Bianka",
    "Blanka",
    "Bogdana",
    "Bogna",
    "Bogumiła",
    "Bogusława",
    "Bolesława",
    "Bożena",
    "Bronisława",
    "Brygida",
    "Cecylia",
    "Celestyna",
    "Celina",
    "Czesława",
    "Dagmara",
    "Daniela",
    "Danka",
    "Danuta",
    "Daria",
    "Diana",
    "Dobromiła",
    "Dobrosława",
    "Dominika",
    "Donata",
    "Dorota",
    "Dosia",
    "Dżesika",
    "Edyta",
    "Ela",
    "Eleonora",
    "Eligia",
    "Eliza",
    "Elwira",
    "Elżbieta",
    "Emilia",
    "Eryka",
    "Estera",
    "Eugenia",
    "Eulalia",
    "Eunika",
    "Ewa",
    "Ewelina",
    "Faustyna",
    "Felicja",
    "Felicyta",
    "Filipina",
    "Florentyna",
    "Franciszka",
    "Fryderyka",
    "Gabriela",
    "Gaja",
    "Genowefa",
    "Gertruda",
    "Gosia",
    "Gracja",
    "Gracjana",
    "Grażyna",
    "Greta",
    "Halina",
    "Halinka",
    "Hania",
    "Hanna",
    "Helena",
    "Helenka",
    "Henryka",
    "Hiacynta",
    "Honorata",
    "Ida",
    "Idalia",
    "Iga",
    "Ignacja",
    "Ilona",
    "Inga",
    "Irena",
    "Irenka",
    "Irmina",
    "Iwona",
    "Iza",
    "Izabela",
    "Izabella",
    "Izolda",
    "Jadwiga",
    "Jadzia",
    "Jaga",
    "Jagienka",
    "Jagna",
    "Jagoda",
    "Jagusia",
    "Janina",
    "Janka",
    "Jarosława",
    "Jaśmina",
    "Joanna",
    "Joasia",
    "Jola",
    "Jolanta",
    "Jowita",
    "Józefa",
    "Józefina",
    "Judyta",
    "Julia",
    "Julianna",
    "Julita",
    "Justyna",
    "Kaja",
    "Kalina",
    "Kamila",
    "Kamilla",
    "Karina",
    "Karola",
    "Karolina",
    "Kasandra",
    "Kasia",
    "Katarzyna",
    "Kazia",
    "Kazimiera",
    "Kinga",
    "Klara",
    "Klaudia",
    "Klementyna",
    "Klotylda",
    "Konstancja",
    "Kornelia",
    "Krysia",
    "Krystiana",
    "Krystyna",
    "Krzysztofa",
    "Ksenia",
    "Kunegunda",
    "Larysa",
    "Laura",
    "Lechosława",
    "Lena",
    "Leokadia",
    "Lesława",
    "Letycja",
    "Lidia",
    "Lidka",
    "Lilia",
    "Liliana",
    "Lilianna",
    "Liwia",
    "Longina",
    "Łucja",
    "Lucyna",
    "Ludmiła",
    "Ludwika",
    "Luiza",
    "Magda",
    "Magdalena",
    "Maja",
    "Maja",
    "Małgorzata",
    "Małgosia",
    "Malina",
    "Malwina",
    "Marcela",
    "Marcelina",
    "Marcjanna",
    "Maria",
    "Marianna",
    "Marietta",
    "Marika",
    "Mariola",
    "Marlena",
    "Marta",
    "Martyna",
    "Maryla",
    "Maryna",
    "Marysia",
    "Marzanna",
    "Marzena",
    "Matylda",
    "Melania",
    "Michalina",
    "Mieczysława",
    "Milena",
    "Milka",
    "Mira",
    "Miriam",
    "Mirka",
    "Mirosława",
    "Monika",
    "Nadia",
    "Nadzieja",
    "Natalia",
    "Natalka",
    "Natasza",
    "Nela",
    "Nikola",
    "Nina",
    "Noemi",
    "Oktawia",
    "Ola",
    "Olga",
    "Olimpia",
    "Oliwia",
    "Otylia",
    "Pati",
    "Patka",
    "Patrycja",
    "Paula",
    "Paulina",
    "Pelagia",
    "Pola",
    "Radomiła",
    "Radosława",
    "Regina",
    "Renata",
    "Renia",
    "Roksana",
    "Romana",
    "Romualda",
    "Róża",
    "Rozalia",
    "Ruta",
    "Sabina",
    "Salomea",
    "Samanta",
    "Sandra",
    "Sara",
    "Seweryna",
    "Sława",
    "Sławomira",
    "Sobiesława",
    "Sonia",
    "Stanisława",
    "Stasia",
    "Stefania",
    "Stefcia",
    "Sybilla",
    "Sylwia",
    "Tamara",
    "Tatiana",
    "Tekla",
    "Teodora",
    "Teodozja",
    "Teofila",
    "Teresa",
    "Tola",
    "Tosia",
    "Ula",
    "Urszula",
    "Wacława",
    "Walentyna",
    "Waleria",
    "Wanda",
    "Wanesa",
    "Wanessa",
    "Wera",
    "Weronika",
    "Wiera",
    "Wiesława",
    "Wiktoria",
    "Wiola",
    "Wioleta",
    "Wioletta",
    "Wisława",
    "Władysława",
    "Wojciecha",
    "Żaklina",
    "Żaneta",
    "Zdzisława",
    "Zofia",
    "Zoja",
    "Zosia",
    "Zula",
    "Zuza",
    "Zuzanna",
    "Zuzia",
    "Zyta"
];

/** @type {Array<String>} */
const OTHER_NAMES = [
    'Alex',
    'Maria',
    'Iwo',
    'Nico'
];

export {LASTNAMES, MALE_NAMES, FEMALE_NAMES, OTHER_NAMES};